### ISSUE TITLE
prefect cloud login fails in this environment

### ISSUE THREAD

**Issue by mrocklin** [coiled/etl-tpch#4]
```
(prefect) etl-tpch:~$ conda activate etl-tpch
(etl-tpch) etl-tpch:~$ prefect cloud login
? How would you like to authenticate? [Use arrows to move; enter to select]
> Log in with a web browser
  Paste an API key
```
```python-traceback
Traceback (most recent call last):
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/prefect/cli/cloud/__init__.py", line 250, in login_with_browser
    await ready_event.wait()
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1778, in wait
    if await self._event.wait():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
           ^^^^^^
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 382, in __call__
    return self.result()
           ^^^^^^^^^^^^^
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/prefect/cli/cloud/__init__.py", line 408, in login
    key = await login_with_browser()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/prefect/cli/cloud/__init__.py", line 249, in login_with_browser
    with anyio.fail_after(10):
  File "/Users/mrocklin/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 119, in __exit__
    raise TimeoutError
TimeoutError
An exception occurred.
```

Everything is fine if I create a fresh conda environment with just prefect in it.  Probably some conflict with one of the other libraries.

**Comment by mrocklin** [comment]
Diffing a good and a bad environment I'm finding:

- Good `prefect                   2.11.5             pyhd8ed1ab_0    conda-forge`
- Bad  `prefect                   2.14.2             pyhd8ed1ab_0    conda-forge`
